apiVersion: apps/v1
kind: Deployment
metadata:
  name: vs-vald-con
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: vs-vald-con
  template:
    metadata:
      labels:
        app: vs-vald-con
    spec:
      volumes:
        - name: serving-certs
          secret:
            secretName: vs-vald-con-certs

      containers:
        - name: vs-vald-con
          image: sayedimran/vs-vald-con:v1.0.0
          imagePullPolicy: Always
          args:
            - "--tls-cert-file=/var/run/secrets/tls/tls.crt"
            - "--tls-private-key-file=/var/run/secrets/tls/tls.key"
            - "--v=4"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: serving-certs
              mountPath: /var/run/secrets/tls/
              readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: vs-vald-con
  namespace: istio-system
spec:
  selector:
    app: vs-vald-con
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
  type: ClusterIP
